...G...PS. [ZBX-5386] fix zbx_free() macro
Before this fix next code would result in an error:

  if (...)
    zbx_free(...);
  else
    ...

The reason is that zbx_free() would be expanded in an "if" statement,
resulting in compiler error:

  error: 'else' without a previous 'if'